services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "39092:39092"
    expose:
      - "9093"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092,OUTSIDETWO://kafka:29092,OUTSIDETRE://bastion:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,OUTSIDETWO:PLAINTEXT,OUTSIDETRE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092,OUTSIDETWO://0.0.0.0:29092,OUTSIDETRE://0.0.0.0:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # dimensioni messaggi
      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 31457280
      KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES: 31457280
      KAFKA_MESSAGE_MAX_BYTES: 31457280

      # retention
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_RETENTION_BYTES: 1073741824

      # topic creati automaticamente
      KAFKA_CREATE_TOPICS: "hfgw_lnf:24:1"

      # tuning (opzionali ma utili)
      KAFKA_NUM_NETWORK_THREADS: 4
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 1048576
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 1048576
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# se vuoi condividere i dati tramite il webserver li trovi dentro kafka:9093
#  web:
#     image: nginx:latest
#     container_name: web
#     ports:
#       - "80:80"
#     volumes:
#       - ${PWD}/dev:/usr/share/nginx/html
